### ISSUE TITLE
Cannot deploy to Heruko

### ISSUE THREAD

**Issue by realmosn** [FabrizioBrancati/SwiftyBot#12]
I cannot deploy to Heroku, I have tried various build packs and also docker and docker-compose but I was never able to get a single response :D/ Seasoned swift developer but I really do not understand how to get this library to work. 

There are other alternatives but due to the structure and code quality I would love to stay with SwiftyBot. any hints ?

**Comment by FabrizioBrancati** [comment]
Are we talking about version 2 or version 3?
I suggest you to try [Vapor’s buildpack](https://github.com/vapor-community/heroku-buildpack), that is what I’m currently using in another Vapor 2 private project.
I will also try to deploy the current 3.0 version this weekend.
I just want to anticipate to you that deploying to Heroku is in the 3.0 scope, so even if it will don’t works on the first try, I will fix it before the final 3.0 release 😉

**Comment by realmosn** [comment]
I’ve had much better luck with the new build pack. Seems to have successfully deployed to Heroku. Note that swift version must be 4.2. 

But when I access the app I see Heroku default page. I assume it has to do something with the custom executable. Any tips on that ?

**Comment by FabrizioBrancati** [comment]
It should use the version inside the `.swift-version` file.
Did you set in your `Procfile` something like this?
`Run serve --env production --hostname 0.0.0.0 --port $PORT`

**Comment by realmosn** [comment]
Setting it from 
`web: Run serve --env production --port $PORT --hostname 0.0.0.0` 
to 
`Run serve --env production --hostname 0.0.0.0 --port $PORT`
results in Timeout and shows application error 

example 
`https://beam0-burbs.herokuapp.com:8080/messenger`

```
request timeout 
```

**Comment by FabrizioBrancati** [comment]
The `web: ` is important, it must be present in your Procfile, I miss it in my previous comment.
Also, when the bot will be up and running, you will se a 404 error, because SwiftyBot is an API only bot, it doesn't provides welcome pages, but it's something that can be added in a 3.1 release maybe 😄

**Comment by realmosn** [comment]
When do you plan to launch 3.0? I can probably help on writing the how to guide. Coming from client side world, I experienced "everything" that could go wrong. I could write a list so that it helps the new comers. 

Build with 
`web: Run serve --env production --hostname 0.0.0.0 --port $PORT`
`SWIFT_BUILD_CONFIGURATION=true` set in env variables. 

will update.  

Also could you please confirm the url format 
`https://beam0-burbs.herokuapp.com:8080/messenger` post and JSON body

**Comment by FabrizioBrancati** [comment]
Yes, absolutely! Write me an email, you can find it the README.md file.

Why did you set `SWIFT_BUILD_CONFIGURATION` to `true`? As I read in the buildpack README it can be used to set the build to `debug`, otherwise it will be for `release`.
If you don't need it, you can omit it.

At last, I didn't understand your question, you want to try it by manually sending a POST request to the bot?

**Comment by realmosn** [comment]
Yes. using Rested; I can manually send a localhost request and get a reply. Additionally I have no other env variable on Heroku 
as per instruction my local app.json looks like this 

```
{
    "telegram" :
    {
        "secret": "XXXXXXXXXXXXXX"
    },
    
    "messenger" :
    {
        "secret": "XXXXXXXXXXXXXX",
        "token": "XXXXXXXXXXXXXX"
    }
}
```

**Comment by FabrizioBrancati** [comment]
Ok, so I can assume that you are using 2.3.3 version.

Let's start with the Telegram part, the final URL will be `(http|https)://{yoururl}/telegram/{telegram_secret}` with an example POST request body like this
```
{
  "message": {
    "chat": {
      "id": 0
    },
    "text": "Hi!",
    "from": {
      "first_name": "Test"
    }
  }
}
```
and you should receive the welcome message as response

**Comment by FabrizioBrancati** [comment]
**Update**: I've been able to successfully deploy the bot to Heroku!
Check the `develop` branch, you will find the new `Procfile` that will deploy the 3.0 bot version.

Check that if you are using the 2.0 bot version the file `app.json` is not pushed to git since it's inside the `.gitignore` file, you should remove that line, but be careful with this, because unless your repo is private, everyone will see your `app.json` file 😉 

P.S.: I also updated my previous comment with the correct JSON body to test the bot!

**Comment by FabrizioBrancati** [comment]
Did my answer resolve your issue? 😄

**Comment by realmosn** [comment]
Hey 👋,
 Yes actually I also noticed that the Run command was giving out errors I tried some different approaches but due to time constraint, decided to go with flowxo to manage my requirements. But I'll try it out again this weekend.

For the time being I set this issue as resolved and will reopen. I will document my test here if someone land here with similar issue.

**Comment by realmosn** [comment]
I wanted to talk about another community project. I will send you an email :) It's gonna be really great.

**Comment by FabrizioBrancati** [comment]
Ok! I can't wait for it! 😄 

Just a little thing about the `Run` command:
For SwiftyBot the command is `SwiftyBot` that's because it's the [name of the executable](https://github.com/FabrizioBrancati/SwiftyBot/blob/develop/Package.swift#L31) declared in the Package.swift file.
In [Vapor's Heroku Buildpack](https://github.com/vapor-community/heroku-buildpack) they wrote `Run` because it's the default for Vapor's project templates.
You can find the right [Procfile here](https://github.com/FabrizioBrancati/SwiftyBot/blob/develop/Procfile).
Hope it will help!
